### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by stalehard** [sendpulse/sendpulse-rest-api-node.js#19]
Hello,
I have a problem with the library related to the following:
```
function getToken(callback){
    if (!callback) {
        callback = function() {}
    }
    var data={
        grant_type:'client_credentials',
        client_id: API_USER_ID,
        client_secret: API_SECRET
    }
    sendRequest( 'oauth/access_token', 'POST', data, false, saveToken );
    function saveToken(data) {
        TOKEN = data.access_token;
        var hashName = md5(API_USER_ID+'::'+API_SECRET);
        fs.writeFileSync(TOKEN_STORAGE+hashName, TOKEN);
        callback(TOKEN)
    }
}
```
**saveToken** function gets a data with token but sometimes she gets object. ```{is_error:1}```
Therefore, the contents of the token is invalid

**Comment by chalcedonyt** [comment]
Getting the same error as well.

**Comment by mrShturman** [comment]
...sometimes she gets an array
![image](https://user-images.githubusercontent.com/4215276/59840617-e775de00-937c-11e9-9cb8-4aab4c96b2db.png)
