### ISSUE TITLE
getToken should be a module export for routinely refreshing the token

### ISSUE THREAD

**Issue by GingerMouseDev** [sendpulse/sendpulse-rest-api-node.js#4]
Hi,

According to the sendpulse docs and tech support the access token needs to be refreshed every hour.

In my node app I first call `init()` on app startup then declare a `setInterval` function to run every hour that calls `getToken()` in order to update the token, but the `getToken()` method isn't made available within the list of 'sendpulse-api' module `exports`. Is there a reason for this please?

Otherwise, it would be necessary to call the `init()` method every hour instead, which has additional statements that have already been called and are unnecessary.

Kind Regards

**Comment by sendpulse** [comment]
Thank you for the feedback. We will add getToken function to exports ASAP.
