### ISSUE TITLE
Token: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ksmike** [sendpulse/sendpulse-rest-api-node.js#41]
Hi Guys,

Found a poorly handled error

```
function sendRequest(path, method, data, useToken, callback) {
    var headers = {};
    headers['Content-Type'] = 'application/json';
    headers['Content-Length'] = Buffer.byteLength(JSON.stringify(data));

    if (useToken && TOKEN.length) { <---- Throws Error Randomly
        headers['Authorization'] = 'Bearer ' + TOKEN;
    }
    if (method === undefined) {
        method = 'POST';
    }
    if (useToken === undefined) {
        useToken = false;
    }
```
This throws this error

```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'length' of undefined",
    "stack": [
        "TypeError: Cannot read property 'length' of undefined",
        "    at sendRequest (/var/task/node_modules/sendpulse-api/api/sendpulse.js:120:27)",
        "    at Object.smtpSendMail (/var/task/node_modules/sendpulse-api/api/sendpulse.js:950:5)",
        "    at /var/task/dist/utils/util.js:228:41",
        "    at saveToken (/var/task/node_modules/sendpulse-api/api/sendpulse.js:209:9)",
        "    at IncomingMessage.<anonymous> (/var/task/node_modules/sendpulse-api/api/sendpulse.js:171:17)",
        "    at IncomingMessage.emit (events.js:326:22)",
        "    at IncomingMessage.EventEmitter.emit (domain.js:483:12)",
        "    at endReadableNT (_stream_readable.js:1241:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}

It's in frequent and I'm sure its because my environment has failed to fully instantiate, but the error on Sendpulse side fails in an ugly way, can you either, validate that the `userToken` and `TOKEN` exists properly. A better error message than the one seen above would be greatly apperciated,

Also if you could go about making this whole process async I'd love you forever!

Please let me know when you update this!

Cheers

```

**Comment by Ksmike** [comment]
This may be related to this endpint -> `    sendRequest('oauth/access_token', 'POST', data, false, saveToken);`

failing

**Comment by linkinkov** [comment]
@Ksmike do you fix this error?

**Comment by Ksmike** [comment]
Yeah it's definitly your oauth endpoint,

```
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}
```
is now the only response i get from your endpoints

**Comment by Ksmike** [comment]
> @Ksmike do you fix this error?

Nope, are you seeing it too?
I've messaged SendPulse Support hopefully we can see a resolution to this soon

**Comment by linkinkov** [comment]
> > @Ksmike do you fix this error?
> 
> Nope, are you seeing it too?
> I've messaged SendPulse Support hopefully we can see a resolution to this soon

Now error is fixed

**Comment by Ksmike** [comment]
> > > @Ksmike do you fix this error?
> > 
> > 
> > Nope, are you seeing it too?
> > I've messaged SendPulse Support hopefully we can see a resolution to this soon
> 
> Now error is fixed

Yeah it's now working my side
thank you!

Can you improve the error handling so the error is more transparent for the end user? It just straight up broke by endpoint no reasoning, think you could start adding better logging / error handling through out?

**Comment by linkinkov** [comment]
> > > > @Ksmike do you fix this error?
> > > 
> > > 
> > > Nope, are you seeing it too?
> > > I've messaged SendPulse Support hopefully we can see a resolution to this soon
> > 
> > 
> > Now error is fixed
> 
> Yeah it's now working my side
> thank you!
> 
> Can you improve the error handling so the error is more transparent for the end user? It just straight up broke by endpoint no reasoning, think you could start adding better logging / error handling through out?

I am not author of lib. Me too faced with this problem, so then oauth service started on sendpulse side, error was gone
